### Data Cleaning and Preprocessing

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [34]:
df = pd.read_csv(r"Titanic_Cleaned.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,Unknown,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,Unknown,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,Unknown,S

In [35]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 891
Columns: 12

In [36]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [37]:
df.info(verbose=True)

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        891 non-null    str
 11  Embarked     891 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [38]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [39]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.361582,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,13.019697,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,22.000000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,35.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [40]:
missing_report = df.isnull().sum().reset_index()

missing_report.columns = ["Column", "Missing Values"]

missing_report

         Column  Missing Values
0   PassengerId               0
1      Survived               0
2        Pclass               0
3          Name               0
4           Sex               0
5           Age               0
6         SibSp               0
7         Parch               0
8        Ticket               0
9          Fare               0
10        Cabin               0
11     Embarked               0

In [41]:
duplicate_count = df.duplicated().sum()

print("Duplicate rows:", duplicate_count)

Duplicate rows: 0

In [11]:
dtype_report = df.dtypes.reset_index()

dtype_report.columns = ["Column", "Data Type"]

dtype_report

         Column Data Type
0   PassengerId     int64
1      Survived     int64
2        Pclass     int64
3          Name       str
4           Sex       str
5           Age   float64
6         SibSp     int64
7         Parch     int64
8        Ticket       str
9          Fare   float64
10        Cabin       str
11     Embarked       str

In [42]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
PassengerId,891.0,446.000000,257.353842,1.00,223.5000,446.0000,668.5,891.0000
Survived,891.0,0.383838,0.486592,0.00,0.0000,0.0000,1.0,1.0000
Pclass,891.0,2.308642,0.836071,1.00,2.0000,3.0000,3.0,3.0000
Age,891.0,29.361582,13.019697,0.42,22.0000,28.0000,35.0,80.0000
SibSp,891.0,0.523008,1.102743,0.00,0.0000,0.0000,1.0,8.0000
Parch,891.0,0.381594,0.806057,0.00,0.0000,0.0000,0.0,6.0000
Fare,891.0,32.204208,49.693429,0.00,7.9104,14.4542,31.0,512.3292

In [43]:
df_clean = df.copy()

In [44]:
df_clean["Age"] = df_clean["Age"].fillna(
    df_clean["Age"].median()
)

In [45]:
df_clean["Cabin"] = df_clean["Cabin"].fillna("Unknown")

In [46]:
df_clean["Embarked"] = df_clean["Embarked"].fillna(
    df_clean["Embarked"].mode()[0]
)

In [47]:
df_clean.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [48]:
duplicate_count = df_clean.duplicated().sum()

print("Duplicate rows before removal:", duplicate_count)

Duplicate rows before removal: 0

In [49]:
df_clean = df_clean.drop_duplicates()

In [50]:
print("Duplicate rows after removal:", df_clean.duplicated().sum())

Duplicate rows after removal: 0

In [51]:
df_clean["Sex"] = df_clean["Sex"].str.lower()

In [52]:
df_clean["Embarked"] = df_clean["Embarked"].str.upper()

In [53]:
df_clean["PassengerId"] = df_clean["PassengerId"].astype(str)

In [54]:
df_clean.dtypes

PassengerId        str
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

In [55]:
def detect_outliers_iqr(data, column):
    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)
    
    IQR = Q3 - Q1
    
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    
    outliers = data[
        (data[column] < lower_bound) |
        (data[column] > upper_bound)
    ]
    
    return outliers, lower_bound, upper_bound

In [28]:
numerical_columns = ["Age", "Fare", "SibSp", "Parch"]

for column in numerical_columns:
    outliers, lower, upper = detect_outliers_iqr(df_clean, column)
    
    print(f"\n{column}")
    print("Lower Bound:", round(lower, 2))
    print("Upper Bound:", round(upper, 2))
    print("Outliers:", len(outliers))

Age
Lower Bound: 2.5
Upper Bound: 54.5
Outliers: 66

Fare
Lower Bound: -26.72
Upper Bound: 65.63
Outliers: 116

SibSp
Lower Bound: -1.5
Upper Bound: 2.5
Outliers: 46

Parch
Lower Bound: 0.0
Upper Bound: 0.0
Outliers: 213

In [56]:
comparison = pd.DataFrame({
    "Metric": [
        "Row Count",
        "Missing Values",
        "Duplicate Rows"
    ],
    "Before Cleaning": [
        len(df),
        df.isnull().sum().sum(),
        df.duplicated().sum()
    ],
    "After Cleaning": [
        len(df_clean),
        df_clean.isnull().sum().sum(),
        df_clean.duplicated().sum()
    ]
})

comparison

           Metric  Before Cleaning  After Cleaning
0       Row Count              891             891
1  Missing Values                0               0
2  Duplicate Rows                0               0

In [30]:
print("Data Types Before Cleaning:")
print(df.dtypes)

print("\nData Types After Cleaning:")
print(df_clean.dtypes)

Data Types Before Cleaning:
PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

Data Types After Cleaning:
PassengerId        str
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

In [57]:
output_file = "Titanic_Cleaned.csv"

df_clean.to_csv(output_file, index=False)

print(f"Cleaned dataset saved successfully as: {output_file}")

Cleaned dataset saved successfully as: Titanic_Cleaned.csv

In [58]:
import os

print("File exists:", os.path.exists(output_file))

File exists: True

In [59]:
print("========== FINAL DATA QUALITY CHECK ==========")

print("\nDataset Shape:")
print(df_clean.shape)

print("\nMissing Values:")
print(df_clean.isnull().sum())

print("\nDuplicate Rows:")
print(df_clean.duplicated().sum())

print("\nData Types:")
print(df_clean.dtypes)

print("\nFirst 5 Rows:")
display(df_clean.head())

print("\nFinal Statistical Summary:")
display(df_clean.describe())

========== FINAL DATA QUALITY CHECK ==========

Dataset Shape:
(891, 12)

Missing Values:
PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

Duplicate Rows:
0

Data Types:
PassengerId        str
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

First 5 Rows:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,Unknown,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,Unknown,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,Unknown,S

Final Statistical Summary:

         Survived      Pclass         Age       SibSp       Parch        Fare
count  891.000000  891.000000  891.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.361582    0.523008    0.381594   32.204208
std      0.486592    0.836071   13.019697    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   22.000000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   35.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200